// Auto-generated code. Do not edit.
namespace myTiles {
    //% fixedInstance jres blockIdentity=images._tile
    export const transparency16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile35 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile36 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile37 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile38 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile39 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile40 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile41 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile42 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile43 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile44 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile45 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile46 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile47 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile48 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile49 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile50 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile51 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile52 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile54 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile55 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile56 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile57 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile58 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile59 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile60 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile61 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile62 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile63 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile64 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile65 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile66 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile67 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile68 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile69 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile70 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile71 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile72 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile73 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile74 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile75 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile76 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile77 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile78 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile79 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile80 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile81 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile82 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile83 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile84 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile85 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile86 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile87 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile88 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile89 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile90 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile91 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile92 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile93 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile94 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile95 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile96 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile97 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile98 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile99 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile100 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile101 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile102 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile103 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile104 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile105 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile106 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile107 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile108 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile109 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile110 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile111 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile112 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile113 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile114 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile115 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile116 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile117 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile118 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile119 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile120 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile121 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile122 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile123 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile124 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile125 = image.ofBuffer(hex``);

}
// Auto-generated code. Do not edit.
